<?php

namespace ContainerWYgWgZj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogPostTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\BlogPostType' shared autowired service.
     *
     * @return \App\Form\BlogPostType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\BlogPostType'] = new \App\Form\BlogPostType();
    }
}
