<?php

namespace ContainerWYgWgZj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_TypeParserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.type_parser' shared service.
     *
     * @return \JMS\Serializer\Type\Parser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['jms_serializer.type_parser'] = new \JMS\Serializer\Type\Parser();
    }
}
