<?php

namespace ContainerWYgWgZj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensorDetailTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\SensorDetailType' shared autowired service.
     *
     * @return \App\Form\SensorDetailType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SensorDetailType'] = new \App\Form\SensorDetailType();
    }
}
