<?php

namespace ContainerWYgWgZj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensorDetailRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Repository\SensorDetailRepository' shared autowired service.
     *
     * @return \App\Repository\SensorDetailRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SensorDetailRepository'] = new \App\Repository\SensorDetailRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
