<?php

namespace ContainerWYgWgZj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Loader_NativeFilesystemService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'twig.loader.native_filesystem' shared service.
     *
     * @return \Twig\Loader\FilesystemLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['twig.loader.native_filesystem'] = $instance = new \Twig\Loader\FilesystemLoader([], 'F:\\sensor_monitor_api');

        $instance->addPath('F:\\sensor_monitor_api\\vendor\\doctrine\\doctrine-bundle/Resources/views', 'Doctrine');
        $instance->addPath('F:\\sensor_monitor_api\\vendor\\doctrine\\doctrine-bundle/Resources/views', '!Doctrine');
        $instance->addPath('F:\\sensor_monitor_api/templates');
        $instance->addPath('F:\\sensor_monitor_api\\vendor\\symfony\\twig-bridge/Resources/views/Form');

        return $instance;
    }
}
