<?php

namespace ContainerHRAbVTi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosRest_Serializer_FlattenExceptionHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_rest.serializer.flatten_exception_handler' shared service.
     *
     * @return \FOS\RestBundle\Serializer\Normalizer\FlattenExceptionHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['fos_rest.serializer.flatten_exception_handler'] = new \FOS\RestBundle\Serializer\Normalizer\FlattenExceptionHandler(new \FOS\RestBundle\Util\ExceptionValueMap([]), new \FOS\RestBundle\Util\ExceptionValueMap([]), true, false);
    }
}
