<?php

namespace ContainerHRAbVTi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensorAlertsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SensorAlertsController' shared autowired service.
     *
     * @return \App\Controller\SensorAlertsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SensorAlertsController'] = $instance = new \App\Controller\SensorAlertsController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\SensorAlertsController', $container));

        return $instance;
    }
}
