<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHRAbVTi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHRAbVTi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHRAbVTi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHRAbVTi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHRAbVTi\App_KernelDevDebugContainer([
    'container.build_hash' => 'HRAbVTi',
    'container.build_id' => '8b75e2b8',
    'container.build_time' => 1636268298,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHRAbVTi');
